import {billingService,BILLING_STATUSES} from './billing.js';
import {repositories} from '../data/repositories.js';
import {visibleForActiveSamples} from '../data/tombstone.js';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=v=>{if(!v)return '—';const d=new Date(`${String(v).slice(0,10)}T12:00:00`);return Number.isNaN(d.getTime())?esc(v):d.toLocaleDateString('es-EC')};
let rows=[],initialized=false;
function toast(msg,error=false){const el=$('toast');if(!el)return;el.textContent=msg;el.className=`toast show${error?' error':''}`;clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='toast',2800)}
function monthOf(r){return String(r.receptionDate||'').slice(5,7)}
function hay(r,q){return !q||[r.code,r.codeFull,r.clientId,r.branch,r.matrixId,r.groupId,r.analyst,r.quotation,r.invoice,r.billingObservation].join(' ').toLowerCase().includes(q)}
function filtered(){const q=($('billingSearch')?.value||'').trim().toLowerCase(),month=$('billingMonth')?.value||'',status=$('billingStatusFilter')?.value||'',type=$('billingTypeFilter')?.value||'';return rows.filter(r=>hay(r,q)&&(!month||monthOf(r)===month)&&(!status||r.billingStatus===status)&&(!type||r.serviceType===type))}
function statusBadge(s){const cls=s==='FACTURADO'?'green':s==='FACTURA PARCIAL'?'blue':s==='EN ESPERA'?'amber':s==='NO FACTURAR'?'purple':'';return `<span class="badge ${cls}">${esc(s||'PENDIENTE')}</span>`}
function renderStats(){const total=rows.length,pending=rows.filter(r=>r.billingStatus==='PENDIENTE').length,fact=rows.filter(r=>r.billingStatus==='FACTURADO').length,partial=rows.filter(r=>r.billingStatus==='FACTURA PARCIAL').length,wait=rows.filter(r=>r.billingStatus==='EN ESPERA').length,no=rows.filter(r=>r.billingStatus==='NO FACTURAR').length;if($('billingStats'))$('billingStats').innerHTML=[['Total',total],['Pendientes',pending],['Facturados',fact],['Factura parcial',partial],['En espera',wait],['No facturar',no]].map(([l,v])=>`<div class="stat"><b>${v}</b><span>${l}</span></div>`).join('');if($('countBilling'))$('countBilling').textContent=total;if($('countBillingControl'))$('countBillingControl').textContent=pending}
function options(current){return BILLING_STATUSES.map(s=>`<option value="${s}" ${s===current?'selected':''}>${s}</option>`).join('')}
function render(){renderStats();const list=filtered();if($('billingVisibleCount'))$('billingVisibleCount').textContent=`${list.length} visibles`;const host=$('billingTable');if(!host)return;host.innerHTML=list.length?`<div class="table-wrap"><table style="min-width:1700px"><thead><tr><th>Código</th><th>Cliente / Sucursal</th><th>Matriz</th><th>Servicio</th><th>Recepción</th><th>Portal</th><th>Cotización</th><th>Factura</th><th>Fecha factura</th><th>Subtotal</th><th>Estado</th><th>Observación administrativa</th><th>Acción</th></tr></thead><tbody>${list.map(r=>`<tr id="billrow_${r.id}"><td><b>${esc(r.code)}</b><div class="muted">${esc(r.year)}</div></td><td><b>${esc(r.clientId)}</b><div class="muted">${esc(r.branch||'—')}</div></td><td>${esc(r.matrixId)}<div class="muted">${esc(r.groupId||'')}</div></td><td>${esc(r.serviceType||'—')}<div class="muted">${esc(r.analyst||'')}</div></td><td>${fmt(r.receptionDate)}</td><td>${fmt(r.portalSentDate)}</td><td><input id="quotation_${r.id}" value="${esc(r.quotation||'')}" data-bill-dirty="${r.id}" placeholder="Cotización"></td><td><input id="invoice_${r.id}" value="${esc(r.invoice||'')}" data-bill-dirty="${r.id}" placeholder="Factura"></td><td><input id="invoiceDate_${r.id}" type="date" value="${esc(r.invoiceDate||'')}" data-bill-dirty="${r.id}"></td><td><input id="subtotal_${r.id}" type="number" min="0" step="0.01" value="${Number(r.subtotal||0)}" data-bill-dirty="${r.id}" style="min-width:110px"></td><td><select id="billingStatus_${r.id}" data-bill-dirty="${r.id}" style="min-width:150px">${options(r.billingStatus||'PENDIENTE')}</select><div style="margin-top:5px">${statusBadge(r.billingStatus)}</div></td><td><textarea id="billingObservation_${r.id}" data-bill-dirty="${r.id}" placeholder="Ej.: Pendiente OC, facturar junto con otra OT, proyecto FT, retención comercial." style="min-width:270px;min-height:58px">${esc(r.billingObservation||'')}</textarea></td><td><button class="btn primary small" data-bill-save="${r.id}">💾 Guardar</button> <button class="btn danger small" data-safe-delete-sample="${r.sampleId}" data-safe-delete-stage="BILLING">Eliminar</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No existen registros de facturación para los filtros seleccionados.</div>'}
function data(id){return {quotation:$(`quotation_${id}`)?.value||'',invoice:$(`invoice_${id}`)?.value||'',invoiceDate:$(`invoiceDate_${id}`)?.value||'',subtotal:$(`subtotal_${id}`)?.value||0,billingStatus:$(`billingStatus_${id}`)?.value||'PENDIENTE',billingObservation:$(`billingObservation_${id}`)?.value||''}}
async function save(id,silent=false){try{await billingService.save(id,data(id),{userId:'LOCAL_USER'});if(!silent)toast('Facturación guardada correctamente.');await api.refresh()}catch(e){toast(e.message||String(e),true)}}
async function saveVisible(){const list=filtered();if(!list.length){toast('No hay registros visibles para guardar.',true);return}try{for(const r of list)await billingService.save(r.id,data(r.id),{userId:'LOCAL_USER'});toast(`${list.length} registro(s) visibles guardados.`);await api.refresh()}catch(e){toast(e.message||String(e),true)}}
function clearFilters(){['billingSearch','billingMonth','billingStatusFilter','billingTypeFilter'].forEach(id=>{if($(id))$(id).value=''});render()}
const api={
 async refresh(){await billingService.reconcileDuplicates();await billingService.ensureFromLaboratory();const [billingRows,samples]=await Promise.all([billingService.all(),repositories.samples.all()]);const activeSampleIds=new Set(samples.map(x=>x.id));rows=visibleForActiveSamples(billingRows,activeSampleIds).sort((a,b)=>(b.receptionDate||'').localeCompare(a.receptionDate||'')||Number(b.code||0)-Number(a.code||0));render()},
 init(){if(initialized)return;initialized=true;['billingSearch'].forEach(id=>$(id)?.addEventListener('input',render));['billingMonth','billingStatusFilter','billingTypeFilter'].forEach(id=>$(id)?.addEventListener('change',render));$('saveVisibleBilling')?.addEventListener('click',saveVisible);$('clearBillingFilters')?.addEventListener('click',clearFilters);document.addEventListener('input',e=>{const x=e.target.closest('[data-bill-dirty]');if(x)$(`billrow_${x.dataset.billDirty}`)?.classList.add('dirty')});document.addEventListener('change',e=>{const x=e.target.closest('[data-bill-dirty]');if(x)$(`billrow_${x.dataset.billDirty}`)?.classList.add('dirty')});document.addEventListener('click',e=>{const b=e.target.closest('[data-bill-save]');if(b)save(b.dataset.billSave)})}
};
export const billingUI=api;
