import {repositories} from '../data/repositories.js';
import {receivableTotals,receivableDisplayStatus} from './receivables.js';

const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const dateOnly=v=>String(v||'').slice(0,10);
const monthKey=v=>dateOnly(v).slice(0,7);
const money=v=>Number(v||0).toLocaleString('es-EC',{style:'currency',currency:'USD',minimumFractionDigits:2});
const AUTH={'1':'1 · INFORMES LISTOS','2':'2 · INFORMES RETENIDOS','3':'3 · COMERCIAL EN SEGUIMIENTO','4':'4 · PROYECTO FT'};
let model=[];
function dateObj(v){const d=new Date(`${dateOnly(v)}T12:00:00`);return Number.isNaN(d.getTime())?null:d}
function daysBetween(a,b){const x=dateObj(a),y=dateObj(b);return x&&y?Math.round((y-x)/86400000):null}
function stageOf(x){
 const {sample:s,lab:l,report:r,billing:b,receivable:c}=x;
 if(c){const st=receivableDisplayStatus(c);if(['PAGADO','ANULADO'].includes(st))return 'FINALIZADA';return 'COBRANZA'}
 if(b){if(b.billingStatus==='NO FACTURAR')return 'FINALIZADA';if(b.billingStatus==='FACTURADO')return 'COBRANZA';return 'FACTURACIÓN'}
 if(r?.portalSentDate||r?.reportStatus==='PORTAL_SENT')return 'FACTURACIÓN';
 if(r?.reportStatus==='PORTAL_PENDING')return 'PORTAL';
 if(r?.reportStatus==='AUTHORIZATION'||r?.realDeliveryDate)return 'AUTORIZACIÓN';
 if(l?.officialEntryAt)return 'LABORATORIO';
 if(s.workflow?.decisionStatus==='DETENIDA')return 'DETENIDA';
 return 'REGISTRADA';
}
async function load(){
 const [samples,labs,reports,billing,receivables]=await Promise.all([repositories.samples.all(),repositories.laboratory.all(),repositories.reports.all(),repositories.billing.all(),repositories.receivables.all()]);
 const by=(a,k='sampleId')=>new Map(a.map(x=>[x[k],x]));const lm=by(labs),rm=by(reports),bm=by(billing),cm=by(receivables);
 model=samples.map(sample=>{const x={sample,lab:lm.get(sample.id)||null,report:rm.get(sample.id)||null,billing:bm.get(sample.id)||null,receivable:cm.get(sample.id)||null};x.stage=stageOf(x);return x});
}
function monthNames(){return [['01','ENERO'],['02','FEBRERO'],['03','MARZO'],['04','ABRIL'],['05','MAYO'],['06','JUNIO'],['07','JULIO'],['08','AGOSTO'],['09','SEPTIEMBRE'],['10','OCTUBRE'],['11','NOVIEMBRE'],['12','DICIEMBRE']]}
function renderFilters(){const y=$('dashYear'),m=$('dashMonth');if(!y||!m)return;const yv=y.value,mv=m.value;const years=[...new Set(model.map(x=>String(x.sample.year||dateOnly(x.sample.samplingDate).slice(0,4))).filter(Boolean))].sort((a,b)=>b.localeCompare(a));y.innerHTML='<option value="">Todos</option>'+years.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');y.value=years.includes(yv)?yv:'';m.innerHTML='<option value="">Todos los meses</option>'+monthNames().map(([v,n])=>`<option value="${v}">${n}</option>`).join('');m.value=monthNames().some(([v])=>v===mv)?mv:''}
function selected(){const y=$('dashYear')?.value||'',m=$('dashMonth')?.value||'';return model.filter(x=>{const d=dateOnly(x.sample.samplingDate||x.sample.createdAt),ky=d.slice(0,4),km=d.slice(5,7);return (!y||ky===y)&&(!m||km===m)})}
function kpiCard(label,value,note,cls=''){return `<div class="dash-kpi ${cls}"><small>${label}</small><b>${value}</b><span>${note}</span></div>`}
function renderKpis(base){const total=base.length,clients=new Set(base.map(x=>x.sample.clientId).filter(Boolean)).size,registered=base.filter(x=>x.stage==='REGISTRADA').length,lab=base.filter(x=>x.stage==='LABORATORIO').length,auth=base.filter(x=>x.stage==='AUTORIZACIÓN').length,portal=base.filter(x=>x.stage==='PORTAL').length,fact=base.filter(x=>x.billing?.billingStatus==='FACTURADO').length,done=base.filter(x=>x.stage==='FINALIZADA').length;let overdue=0;base.forEach(x=>{if(x.lab?.maxReportDate&&!x.report?.realDeliveryDate&&dateObj(x.lab.maxReportDate)<dateObj(new Date().toISOString().slice(0,10)))overdue++});$('dashKpis').innerHTML=[kpiCard('Muestras',total,'Período seleccionado','blue'),kpiCard('Clientes',clients,'Clientes únicos','cyan'),kpiCard('Registradas',registered,'Sin ingreso oficial','green'),kpiCard('Laboratorio',lab,'En proceso / informe pendiente','blue'),kpiCard('Autorización',auth,'Pendientes de decisión','purple'),kpiCard('Portal',portal,'Pendientes de publicación','green'),kpiCard('Facturadas',fact,'Con factura emitida','green'),kpiCard('Finalizadas',done,'Cierre administrativo','green'),kpiCard('Vencidas SLA',overdue,'Requieren atención','red')].join('')}
function renderFlow(base){const labels=[['REGISTRADA','Registradas'],['LABORATORIO','Laboratorio'],['AUTORIZACIÓN','Autorización'],['PORTAL','Portal'],['FACTURACIÓN','Facturación'],['COBRANZA','Cobranza'],['FINALIZADA','Finalizadas']];$('dashFlow').innerHTML=labels.map(([k,l])=>`<div class="dash-flow-step"><b>${base.filter(x=>x.stage===k).length}</b><small>${l}</small></div>`).join('')}
function last12(){const n=new Date(),a=[];for(let i=11;i>=0;i--){const d=new Date(n.getFullYear(),n.getMonth()-i,1);a.push(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`)}return a}
function shortMonth(k){const d=new Date(`${k}-01T12:00:00`);return d.toLocaleDateString('es-EC',{month:'short'}).replace('.','').toUpperCase()}
function renderMonthly(){const months=last12(),cnt=Object.fromEntries(months.map(k=>[k,0]));model.forEach(x=>{const k=monthKey(x.sample.samplingDate||x.sample.createdAt);if(k in cnt)cnt[k]++});const max=Math.max(1,...Object.values(cnt));$('dashMonthly').innerHTML=months.map(k=>`<div class="dash-month"><div class="dash-month-track"><div class="dash-month-bar" style="height:${Math.max(2,Math.round(cnt[k]/max*100))}%" title="${cnt[k]} muestra(s)"></div></div><b>${cnt[k]}</b><small>${shortMonth(k)}</small></div>`).join('')}
function renderMatrices(base){const d={};base.forEach(x=>{const k=x.sample.matrixId||'SIN MATRIZ';d[k]=(d[k]||0)+1});const rows=Object.entries(d).sort((a,b)=>b[1]-a[1]),max=Math.max(1,...rows.map(x=>x[1]));$('dashMatrices').innerHTML=rows.length?rows.slice(0,10).map(([n,v],i)=>`<div class="dash-rank-row"><span class="dash-rank-num">${i+1}</span><span class="dash-rank-name">${esc(n)}</span><span class="dash-rank-value">${v}</span><div class="dash-rank-bar"><i style="width:${Math.round(v/max*100)}%"></i></div></div>`).join(''):'<div class="dash-empty">Sin datos.</div>'}
function donut(el,pct,a='#17b26a',b='#e7eee9',label=''){el.innerHTML=`<div class="dash-donut-layout"><div class="dash-donut" style="background:conic-gradient(${a} 0 ${pct}%,${b} ${pct}% 100%)"><div class="dash-donut-center"><b>${pct}%</b><small>${label}</small></div></div></div>`}
function renderCompliance(base){const evals=base.filter(x=>x.lab?.maxReportDate&&x.report?.realDeliveryDate),ok=evals.filter(x=>dateOnly(x.report.realDeliveryDate)<=dateOnly(x.lab.maxReportDate)).length,pct=evals.length?Math.round(ok/evals.length*100):0;const el=$('dashCompliance');el.innerHTML=`<div class="dash-donut-layout"><div class="dash-donut" style="background:conic-gradient(#17b26a 0 ${pct}%,#d92d20 ${pct}% 100%)"><div class="dash-donut-center"><b>${pct}%</b><small>Cumplimiento</small></div></div><div class="dash-legend"><div><i style="background:#17b26a"></i>En plazo <b>${ok}</b></div><div><i style="background:#d92d20"></i>Fuera de plazo <b>${Math.max(0,evals.length-ok)}</b></div><div>Evaluables <b>${evals.length}</b></div></div></div>`}
function renderAuth(base){const counts=['1','2','3','4'].map(k=>[k,base.filter(x=>x.report?.authorizationStatus===k).length]),max=Math.max(1,...counts.map(x=>x[1]));$('dashAuthorization').innerHTML=counts.map(([k,n])=>`<div class="dash-stage-row"><span>${esc(AUTH[k].replace(/^\d · /,''))}</span><div class="dash-track"><i style="width:${Math.round(n/max*100)}%"></i></div><b>${n}</b></div>`).join('')}
function renderService(base){const labs=base.filter(x=>x.lab?.officialEntryAt),intern=labs.filter(x=>x.lab.serviceType==='INTERNO').length,extern=labs.filter(x=>x.lab.serviceType==='EXTERNO').length,pct=labs.length?Math.round(intern/labs.length*100):0;$('dashServiceType').innerHTML=`<div class="dash-donut-layout"><div class="dash-donut" style="background:conic-gradient(#175cd3 0 ${pct}%,#f79009 ${pct}% 100%)"><div class="dash-donut-center"><b>${labs.length}</b><small>Ingresos</small></div></div><div class="dash-legend"><div><i style="background:#175cd3"></i>Interno <b>${intern}</b></div><div><i style="background:#f79009"></i>Externo <b>${extern}</b></div></div></div>`}
function renderFinancial(base){let billed=0,paid=0,balance=0,adjust=0;for(const x of base){if(x.receivable){const t=receivableTotals(x.receivable);billed+=t.total;paid+=t.paid;balance+=t.balance;adjust+=t.retentions+t.creditNotes}else if(x.billing?.billingStatus==='FACTURADO'){billed+=Number(x.billing.subtotal||0)}}const recovery=billed?paid/billed*100:0;$('dashFinancial').innerHTML=[['Facturado',money(billed)],['Cobrado',money(paid)],['Saldo',money(balance)],['Recuperado',recovery.toFixed(1)+'%']].map(([l,v])=>`<div class="dash-money"><small>${l}</small><b>${v}</b></div>`).join('')}
function renderAlerts(base){const a=[];const today=new Date().toISOString().slice(0,10);for(const x of base){const s=x.sample;if(x.lab?.maxReportDate&&!x.report?.realDeliveryDate&&dateOnly(x.lab.maxReportDate)<today)a.push({c:'red',t:`${s.code} · ${s.clientId}`,d:`Informe vencido · fecha máxima ${x.lab.maxReportDate}`});if(['2','3'].includes(x.report?.authorizationStatus))a.push({c:'',t:`${s.code} · ${s.clientId}`,d:AUTH[x.report.authorizationStatus]});if(x.receivable&&receivableDisplayStatus(x.receivable)==='VENCIDO')a.push({c:'red',t:`Factura ${x.receivable.invoice||x.billing?.invoice||'—'} · ${s.clientId}`,d:`Cartera vencida · saldo ${money(receivableTotals(x.receivable).balance)}`});if(x.billing?.billingStatus==='EN ESPERA')a.push({c:'',t:`${s.code} · ${s.clientId}`,d:'Facturación en espera'})}$('dashAlerts').innerHTML=a.length?a.slice(0,20).map(x=>`<div class="dash-alert ${x.c}"><div><b>${esc(x.t)}</b><span>${esc(x.d)}</span></div></div>`).join(''):'<div class="dash-alert green"><div><b>Sin alertas críticas</b><span>No se detectan expedientes que requieran atención inmediata en el período.</span></div></div>'}
function renderMatrixMonth(base){const months=[...new Set(base.map(x=>monthKey(x.sample.samplingDate||x.sample.createdAt)).filter(x=>/^\d{4}-\d{2}$/.test(x)))].sort().slice(-12),mats=[...new Set(base.map(x=>x.sample.matrixId||'SIN MATRIZ'))].sort((a,b)=>a.localeCompare(b,'es'));if(!months.length||!mats.length){$('dashMatrixMonth').innerHTML='<div class="dash-empty">Sin datos.</div>';return}const cells={};base.forEach(x=>{const m=x.sample.matrixId||'SIN MATRIZ',k=monthKey(x.sample.samplingDate||x.sample.createdAt);cells[`${m}|${k}`]=(cells[`${m}|${k}`]||0)+1});$('dashMatrixMonth').innerHTML=`<table><thead><tr><th>Matriz</th>${months.map(k=>`<th>${shortMonth(k)} ${k.slice(2,4)}</th>`).join('')}<th>Total</th></tr></thead><tbody>${mats.map(m=>{const vals=months.map(k=>cells[`${m}|${k}`]||0);return `<tr><td><b>${esc(m)}</b></td>${vals.map(v=>`<td>${v||'—'}</td>`).join('')}<td><b>${vals.reduce((a,b)=>a+b,0)}</b></td></tr>`}).join('')}</tbody></table>`}
function renderMonthlyTable(){const months=last12();const rows=months.map(k=>{const a=model.filter(x=>monthKey(x.sample.samplingDate||x.sample.createdAt)===k);if(!a.length)return null;return {k,n:a.length,clients:new Set(a.map(x=>x.sample.clientId).filter(Boolean)).size,lab:a.filter(x=>x.lab?.officialEntryAt).length,portal:a.filter(x=>x.report?.portalSentDate).length,fact:a.filter(x=>x.billing?.billingStatus==='FACTURADO').length,done:a.filter(x=>x.stage==='FINALIZADA').length}}).filter(Boolean).reverse();$('dashMonthlyTable').innerHTML=rows.length?`<table><thead><tr><th>Mes</th><th>Muestras</th><th>Clientes</th><th>Ingreso Lab.</th><th>Portal enviado</th><th>Facturadas</th><th>Finalizadas</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${shortMonth(x.k)} ${x.k.slice(0,4)}</b></td><td>${x.n}</td><td>${x.clients}</td><td>${x.lab}</td><td>${x.portal}</td><td>${x.fact}</td><td>${x.done}</td></tr>`).join('')}</tbody></table>`:'<div class="dash-empty">Sin actividad mensual.</div>'}
function render(){renderFilters();const base=selected();renderKpis(base);renderFlow(base);renderMonthly();renderMatrices(base);renderCompliance(base);renderAuth(base);renderService(base);renderFinancial(base);renderAlerts(base);renderMatrixMonth(base);renderMonthlyTable();if($('countDashboard'))$('countDashboard').textContent=model.length}
export const dashboardUI={
 init(){['dashYear','dashMonth'].forEach(id=>$(id)?.addEventListener('change',render));$('dashCurrentMonth')?.addEventListener('click',()=>{const n=new Date();if($('dashYear'))$('dashYear').value=String(n.getFullYear());if($('dashMonth'))$('dashMonth').value=String(n.getMonth()+1).padStart(2,'0');render()});$('dashClear')?.addEventListener('click',()=>{if($('dashYear'))$('dashYear').value='';if($('dashMonth'))$('dashMonth').value='';render()})},
 async refresh(){await load();render();return model.length}
};
