import {repositories} from '../data/repositories.js';
import {receivableTotals,receivableDisplayStatus} from './receivables.js';

const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const dateOnly=v=>String(v||'').slice(0,10);
const fmt=v=>{if(!v)return '—';const d=new Date(`${dateOnly(v)}T12:00:00`);return Number.isNaN(d.getTime())?esc(v):d.toLocaleDateString('es-EC')};
const money=v=>Number(v||0).toLocaleString('es-EC',{style:'currency',currency:'USD',minimumFractionDigits:2});
const today=()=>new Date().toISOString().slice(0,10);
const monthKey=v=>dateOnly(v).slice(0,7);
function daysBetween(a,b){if(!a||!b)return null;const x=new Date(`${dateOnly(a)}T12:00:00`),y=new Date(`${dateOnly(b)}T12:00:00`);if(Number.isNaN(x)||Number.isNaN(y))return null;return Math.round((y-x)/86400000)}
function daysUntil(v){if(!v)return null;return daysBetween(today(),v)}
function codeNum(v){const m=String(v||'').match(/\d+/g);return m?Number(m.join(''))||0:0}
const AUTH={'1':'1 · INFORMES LISTOS','2':'2 · INFORMES RETENIDOS','3':'3 · COMERCIAL EN SEGUIMIENTO','4':'4 · PROYECTO FT'};
const STAGES=['MONITOREO','DETENIDA','LABORATORIO','INFORME PENDIENTE','AUTORIZACIÓN','PORTAL CLIENTE','FACTURACIÓN','CUENTAS POR COBRAR','FINALIZADA'];
const STEP_LABELS=['Muestra registrada','Ingreso oficial Lab.','Entrega real','Autorización','Portal cliente','Facturación','Cobranza','Cierre'];
let model=[],selectedId='';

function stageOf(x){
  if(x.receivable){const rs=receivableDisplayStatus(x.receivable);if(['PAGADO','ANULADO'].includes(rs))return 'FINALIZADA';return 'CUENTAS POR COBRAR'}
  if(x.billing){if(x.billing.billingStatus==='NO FACTURAR')return 'FINALIZADA';if(x.billing.billingStatus==='FACTURADO')return 'CUENTAS POR COBRAR';return 'FACTURACIÓN'}
  if(x.report){if(x.report.reportStatus==='PORTAL_SENT')return 'FACTURACIÓN';if(x.report.reportStatus==='PORTAL_PENDING')return 'PORTAL CLIENTE';if(x.report.reportStatus==='AUTHORIZATION')return 'AUTORIZACIÓN';return 'INFORME PENDIENTE'}
  if(x.lab)return x.lab.officialEntryAt?'INFORME PENDIENTE':'LABORATORIO';
  if(x.sample.workflow?.decisionStatus==='DETENIDA')return 'DETENIDA';
  return 'MONITOREO';
}
function stepData(x){const s=x.sample,l=x.lab,r=x.report,b=x.billing,c=x.receivable;const billDone=!!b&&['FACTURADO','NO FACTURAR'].includes(b.billingStatus);const collectionDone=!!c&&['PAGADO','ANULADO'].includes(receivableDisplayStatus(c));return [
  {done:true,date:s.samplingDate||s.createdAt,detail:`${s.matrixId||'—'} · ${s.groupId||'—'} · ${s.workflow?.decisionStatus||'CONTINUAR'}`},
  {done:!!l?.officialEntryAt,date:l?.receptionDate||l?.officialEntryAt,detail:l?.officialEntryAt?`${l.analyst||'Sin analista'} · ${l.serviceType||'—'} · SLA ${l.slaDays||'—'} días`:'Pendiente de ingreso oficial'},
  {done:!!r?.realDeliveryDate,date:r?.realDeliveryDate,detail:r?.realDeliveryDate?'Fecha real registrada':'Pendiente de entrega real'},
  {done:!!r?.authorizationDate,date:r?.authorizationDate,detail:r?.authorizationStatus?AUTH[r.authorizationStatus]||r.authorizationStatus:'Pendiente de autorización'},
  {done:!!r?.portalSentDate,date:r?.portalSentDate,detail:r?.portalSentDate?'Publicado / enviado al portal':'Pendiente de portal'},
  {done:billDone,date:b?.invoiceDate||b?.billingUpdatedAt,detail:b?`${b.billingStatus||'PENDIENTE'}${b.invoice?' · Factura '+b.invoice:''}`:'Pendiente de facturación'},
  {done:collectionDone,date:c?.paymentDate||c?.collectionUpdatedAt,detail:c?`${receivableDisplayStatus(c)} · Saldo ${money(receivableTotals(c).balance)}`:'Pendiente de cobranza'},
  {done:collectionDone||b?.billingStatus==='NO FACTURAR',date:c?.paymentDate||b?.billingUpdatedAt,detail:collectionDone?'Cartera cerrada':b?.billingStatus==='NO FACTURAR'?'No facturable':'Proceso administrativo abierto'}
]}
function progress(x){const steps=stepData(x),n=steps.filter(z=>z.done).length;return {n,total:steps.length,pct:Math.round(n/steps.length*100),steps}}
function deadline(x){const max=x.lab?.maxReportDate||x.report?.maxReportDate||'';if(!max)return {key:'SIN_FECHA',label:'SIN FECHA',cls:''};if(x.report?.realDeliveryDate){const n=daysBetween(max,x.report.realDeliveryDate);return n>0?{key:'VENCIDO',label:`ENTREGADO +${n} d`,cls:'danger'}:{key:'EN_PLAZO',label:'ENTREGADO EN PLAZO',cls:'done'}}const n=daysUntil(max);if(n<0)return {key:'VENCIDO',label:`VENCIDO · ${Math.abs(n)} d`,cls:'danger'};if(n<=2)return {key:'CRITICO',label:`${n} d RESTANTE`,cls:'warn'};return {key:'EN_PLAZO',label:`EN PLAZO · ${n} d`,cls:'done'}}
function stageClass(s){if(s==='LABORATORIO')return 'lab';if(s==='INFORME PENDIENTE')return 'report';if(s==='AUTORIZACIÓN')return 'auth';if(s==='PORTAL CLIENTE')return 'portal';if(s==='FACTURACIÓN')return 'billing';if(s==='CUENTAS POR COBRAR')return 'collection';if(s==='FINALIZADA')return 'finished';if(s==='DETENIDA')return 'stopped';return ''}
async function loadModel(){const [samples,labs,reports,billing,receivables]=await Promise.all([repositories.samples.all(),repositories.laboratory.all(),repositories.reports.all(),repositories.billing.all(),repositories.receivables.all()]);const labBySample=new Map(labs.map(x=>[x.sampleId,x])),reportBySample=new Map(reports.map(x=>[x.sampleId,x])),billBySample=new Map(billing.map(x=>[x.sampleId,x])),recBySample=new Map(receivables.map(x=>[x.sampleId,x]));model=samples.map(sample=>{const x={sample,lab:labBySample.get(sample.id)||null,report:reportBySample.get(sample.id)||null,billing:billBySample.get(sample.id)||null,receivable:recBySample.get(sample.id)||null};x.stage=stageOf(x);x.progress=progress(x);x.deadline=deadline(x);return x})}
function filters(){return {q:($('trackingSearch')?.value||'').trim().toLowerCase(),stage:$('trackingStage')?.value||'',matrix:$('trackingMatrix')?.value||'',deadline:$('trackingDeadline')?.value||'',month:$('trackingMonth')?.value||''}}
function visible(){const f=filters();return model.filter(x=>{const s=x.sample,l=x.lab,r=x.report,b=x.billing,c=x.receivable;const text=[s.code,s.codeFull,s.clientId,s.branch,s.matrixId,s.groupId,l?.analyst,b?.invoice,b?.quotation,c?.invoice,x.stage].join(' ').toLowerCase();return (!f.q||text.includes(f.q))&&(!f.stage||x.stage===f.stage)&&(!f.matrix||s.matrixId===f.matrix)&&(!f.deadline||x.deadline.key===f.deadline)})}
function renderFilterOptions(){const st=$('trackingStage'),mx=$('trackingMatrix');if(!st||!mx)return;const sv=st.value,mv=mx.value;st.innerHTML='<option value="">Todas las etapas</option>'+STAGES.map(x=>`<option>${x}</option>`).join('');st.value=STAGES.includes(sv)?sv:'';const matrices=[...new Set(model.map(x=>x.sample.matrixId).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));mx.innerHTML='<option value="">Todas las matrices</option>'+matrices.map(x=>`<option>${esc(x)}</option>`).join('');mx.value=matrices.includes(mv)?mv:''}
function renderKpis(){const total=model.length,active=model.filter(x=>x.stage!=='FINALIZADA').length,lab=model.filter(x=>x.stage==='LABORATORIO').length,pending=model.filter(x=>x.stage==='INFORME PENDIENTE').length,auth=model.filter(x=>x.stage==='AUTORIZACIÓN').length,portal=model.filter(x=>x.stage==='PORTAL CLIENTE').length,billing=model.filter(x=>x.stage==='FACTURACIÓN').length,collection=model.filter(x=>x.stage==='CUENTAS POR COBRAR').length,done=model.filter(x=>x.stage==='FINALIZADA').length,over=model.filter(x=>x.deadline.key==='VENCIDO').length,avg=total?Math.round(model.reduce((a,x)=>a+x.progress.pct,0)/total):0;const k=[['Expedientes',total,'Total trazable','blue'],['Activos',active,'Proceso abierto','cyan'],['Laboratorio',lab,'Pendientes de ingreso','blue'],['Informes',pending,'Sin entrega real','amber'],['Autorización',auth,'Pendientes de decisión','purple'],['Portal',portal,'Listos para publicación','green'],['Facturación',billing,'Control administrativo','amber'],['Cobranza',collection,'Cartera abierta','blue'],['Finalizadas',done,'Cierre administrativo','green'],['Vencidas',over,'Informe fuera de SLA','red'],['Avance promedio',avg+'%','Progreso global','blue']];$('trackingKpis').innerHTML=k.map(x=>`<div class="trace-summary-card ${x[3]}"><div class="trace-summary-label">${x[0]}</div><div class="trace-summary-value">${x[1]}</div><small>${x[2]}</small></div>`).join('');if($('countTracking'))$('countTracking').textContent=total;if($('countTrackingSub'))$('countTrackingSub').textContent=active}
function monthRange(){const now=new Date();const a=[];for(let i=11;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);a.push(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`)}return a}
function monthLabel(k){const d=new Date(`${k}-01T12:00:00`);return d.toLocaleDateString('es-EC',{month:'short'}).replace('.','').toUpperCase()}
function analyticsRows(){const f=filters(),base=f.month?model.filter(x=>monthKey(x.sample.samplingDate||x.sample.createdAt)===f.month):model;return base}
function renderAnalytics(){const base=analyticsRows(),total=base.length,clients=new Set(base.map(x=>x.sample.clientId).filter(Boolean)).size,stopped=base.filter(x=>x.sample.workflow?.decisionStatus==='DETENIDA').length,over=base.filter(x=>x.deadline.key==='VENCIDO').length,done=base.filter(x=>x.stage==='FINALIZADA').length,avg=total?Math.round(base.reduce((a,x)=>a+x.progress.pct,0)/total):0;const complianceDen=base.filter(x=>x.lab?.maxReportDate&&x.report?.realDeliveryDate),onTime=complianceDen.filter(x=>dateOnly(x.report.realDeliveryDate)<=dateOnly(x.lab.maxReportDate)).length,compliance=complianceDen.length?Math.round(onTime/complianceDen.length*100):0;$('trackingAnalyticsKpis').innerHTML=[['OT / Muestras',total,'Período seleccionado','blue'],['Clientes',clients,'Clientes únicos','cyan'],['Detenidas',stopped,'Decisión operativa','red'],['Vencidas',over,'SLA de informe','amber'],['Finalizadas',done,'Cierre completo','green'],['Avance',avg+'%','Promedio del período','purple']].map(x=>`<div class="analytics-kpi ${x[3]}"><small>${x[0]}</small><b>${x[1]}</b><span>${x[2]}</span></div>`).join('');
 const months=monthRange(),counts=Object.fromEntries(months.map(k=>[k,0]));model.forEach(x=>{const k=monthKey(x.sample.samplingDate||x.sample.createdAt);if(k in counts)counts[k]++});const max=Math.max(1,...Object.values(counts));$('trackingMonthlyChart').innerHTML=months.map(k=>`<div class="month-col"><div class="bar-wrap"><div class="month-bar" style="height:${Math.max(2,Math.round(counts[k]/max*100))}%" title="${counts[k]} expediente(s)"></div></div><strong>${counts[k]}</strong><small>${monthLabel(k)}</small></div>`).join('');
 const late=Math.max(0,complianceDen.length-onTime);$('trackingCompliance').innerHTML=`<div class="donut-layout"><div class="donut" style="background:conic-gradient(#17b26a 0 ${compliance}%,#d92d20 ${compliance}% 100%)"><div class="donut-center"><b>${compliance}%</b><small>Cumplimiento</small></div></div><div class="donut-legend"><div><i style="background:#17b26a"></i>En plazo: <b>${onTime}</b></div><div><i style="background:#d92d20"></i>Fuera de plazo: <b>${late}</b></div><div>Con entrega evaluable: <b>${complianceDen.length}</b></div></div></div>`;
 const stageCounts=STAGES.map(s=>[s,base.filter(x=>x.stage===s).length]).filter(x=>x[1]>0),stageMax=Math.max(1,...stageCounts.map(x=>x[1]));$('trackingStagesChart').innerHTML=stageCounts.length?stageCounts.map(([s,n])=>`<div class="stage-row"><span>${esc(s)}</span><div class="stage-track"><i style="width:${Math.round(n/stageMax*100)}%"></i></div><span class="stage-count">${n}</span></div>`).join(''):'<div class="empty">Sin datos.</div>';
 const byM={};base.forEach(x=>{const k=x.sample.matrixId||'SIN MATRIZ';byM[k]=(byM[k]||0)+1});const ranks=Object.entries(byM).sort((a,b)=>b[1]-a[1]).slice(0,6),rmax=Math.max(1,...ranks.map(x=>x[1]));$('trackingMatrixRank').innerHTML=ranks.length?ranks.map(([name,n],i)=>`<div class="rank-item"><span class="rank-num">${i+1}</span><span class="rank-name">${esc(name)}</span><span class="rank-value">${n}</span><div class="rank-bar"><i style="width:${Math.round(n/rmax*100)}%"></i></div></div>`).join(''):'<div class="empty">Sin datos.</div>';
 let billed=0,collected=0,balance=0,ret=0;base.forEach(x=>{if(x.receivable){const t=receivableTotals(x.receivable);billed+=t.total;collected+=t.paid;balance+=t.balance;ret+=t.retentions+t.creditNotes}else if(x.billing?.billingStatus==='FACTURADO'){billed+=Number(x.billing.subtotal||0)}});const recovery=billed?collected/billed*100:0;$('trackingFinancial').innerHTML=[['Valor facturado',money(billed)],['Valor cobrado',money(collected)],['Saldo pendiente',money(balance)],['Recuperación',recovery.toFixed(1)+'%']].map(x=>`<div class="financial-card"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');
 const monthly=months.map(k=>{const rows=model.filter(x=>monthKey(x.sample.samplingDate||x.sample.createdAt)===k),cl=new Set(rows.map(x=>x.sample.clientId).filter(Boolean)).size,ov=rows.filter(x=>x.deadline.key==='VENCIDO').length,av=rows.length?Math.round(rows.reduce((a,x)=>a+x.progress.pct,0)/rows.length):0,fin=rows.filter(x=>x.stage==='FINALIZADA').length;return {k,n:rows.length,cl,ov,av,fin}}).filter(x=>x.n);$('trackingMonthlyTable').innerHTML=monthly.length?`<table><thead><tr><th>Mes</th><th>Expedientes</th><th>Clientes</th><th>Vencidas</th><th>Finalizadas</th><th>Cumplimiento</th><th>Avance prom.</th></tr></thead><tbody>${monthly.slice().reverse().map(x=>`<tr><td><b>${monthLabel(x.k)} ${x.k.slice(0,4)}</b></td><td>${x.n}</td><td>${x.cl}</td><td>${x.ov}</td><td>${x.fin}</td><td>${x.n?Math.round((x.n-x.ov)/x.n*100):0}%</td><td>${x.av}%</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Sin actividad mensual.</div>'
}
function renderTable(){const rows=visible().sort((a,b)=>{const ad=dateOnly(a.sample.samplingDate),bd=dateOnly(b.sample.samplingDate);if(ad!==bd)return bd.localeCompare(ad);return codeNum(b.sample.code)-codeNum(a.sample.code)});$('trackingVisible').textContent=`${rows.length} visible${rows.length===1?'':'s'}`;if(rows.length&&(!selectedId||!rows.some(x=>x.sample.id===selectedId)))selectedId=rows[0].sample.id;if(!rows.length)selectedId='';$('trackingTable').innerHTML=rows.length?`<div class="table-wrap" style="border:0;border-radius:0"><table><thead><tr><th>Código</th><th>Cliente / Sucursal</th><th>Matriz</th><th>Analista</th><th>Etapa actual</th><th>Avance</th><th>Plazo informe</th><th>Factura / Cobro</th></tr></thead><tbody>${rows.map(x=>{const s=x.sample,b=x.billing,c=x.receivable,p=x.progress,d=x.deadline;return `<tr class="trace-row ${selectedId===s.id?'selected':''}" data-track-id="${s.id}"><td><div class="trace-code">${esc(s.code)}</div><small>${esc(s.year||'')}</small></td><td><b>${esc(s.clientId||'Sin cliente')}</b><div class="muted">${esc(s.branch||'—')}</div></td><td><b>${esc(s.matrixId||'—')}</b><div class="muted">${esc(s.groupId||'—')}</div></td><td>${esc(x.lab?.analyst||'Sin asignar')}</td><td><span class="trace-stage-chip ${stageClass(x.stage)}">${esc(x.stage)}</span></td><td><div class="trace-progress"><span style="width:${p.pct}%"></span></div><div class="trace-progress-label">${p.pct}% · ${p.n}/${p.total}</div></td><td><span class="status-pill ${d.cls}">${esc(d.label)}</span><br><small>${fmt(x.lab?.maxReportDate||x.report?.maxReportDate)}</small></td><td>${b?.invoice?`<b>${esc(b.invoice)}</b>`:'—'}<div class="muted">${c?`${receivableDisplayStatus(c)} · ${money(receivableTotals(c).balance)}`:b?.billingStatus||''}</div></td></tr>`}).join('')}</tbody></table></div>`:'<div class="trace-empty">No hay expedientes que coincidan con los filtros.</div>';renderDetail()}
function renderDetail(){const box=$('trackingDetail');if(!box)return;const x=model.find(v=>v.sample.id===selectedId);if(!x){box.innerHTML='<div class="trace-empty"><b>Sin expediente seleccionado</b><p>Seleccione una fila para ver toda la trazabilidad.</p></div>';return}const s=x.sample,l=x.lab,r=x.report,b=x.billing,c=x.receivable,p=x.progress,d=x.deadline,steps=p.steps,firstPending=steps.findIndex(z=>!z.done);box.innerHTML=`<div class="trace-side-header"><div><h3>${esc(s.code||'Muestra')}</h3><p>${esc(s.clientId||'')}${s.branch?' · '+esc(s.branch):''}</p></div><span class="trace-stage-chip ${stageClass(x.stage)}">${esc(x.stage)}</span></div><div class="trace-side-grid"><div class="trace-side-field"><small>Matriz / Grupo</small><b>${esc(s.matrixId||'—')} · ${esc(s.groupId||'—')}</b></div><div class="trace-side-field"><small>Analista</small><b>${esc(l?.analyst||'Sin asignar')}</b></div><div class="trace-side-field"><small>Recepción</small><b>${fmt(l?.receptionDate||s.receivedDate)}</b></div><div class="trace-side-field"><small>Fecha máxima</small><b>${fmt(l?.maxReportDate)}</b></div><div class="trace-side-field"><small>Plazo</small><b><span class="status-pill ${d.cls}">${esc(d.label)}</span></b></div><div class="trace-side-field"><small>Autorización</small><b>${esc(AUTH[r?.authorizationStatus]||'—')}</b></div><div class="trace-side-field"><small>Factura</small><b>${esc(b?.invoice||'—')}</b></div><div class="trace-side-field"><small>Cobranza</small><b>${esc(c?receivableDisplayStatus(c):'—')}</b></div></div><div class="trace-side-progress"><div class="trace-progress"><span style="width:${p.pct}%"></span></div><b style="display:block;margin-top:6px">Avance general: ${p.pct}%</b><small>${p.n} de ${p.total} etapas completadas</small></div><div class="trace-timeline">${STEP_LABELS.map((label,i)=>{const z=steps[i],cur=!z.done&&i===firstPending;return `<div class="trace-timeline-row ${z.done?'done':cur?'current':''}"><div class="trace-timeline-icon">${z.done?'✓':i+1}</div><div><b>${label}</b><br><small>${esc(z.detail||'')}</small></div><small>${fmt(z.date)}</small></div>`}).join('')}</div>`}
function render(){renderFilterOptions();renderKpis();renderAnalytics();renderTable()}
export const trackingUI={
 init(){['trackingSearch'].forEach(id=>$(id)?.addEventListener('input',render));['trackingStage','trackingMatrix','trackingDeadline','trackingMonth'].forEach(id=>$(id)?.addEventListener('change',render));$('trackingClear')?.addEventListener('click',()=>{['trackingSearch','trackingStage','trackingMatrix','trackingDeadline'].forEach(id=>{if($(id))$(id).value=''});render()});$('trackingCurrentMonth')?.addEventListener('click',()=>{if($('trackingMonth'))$('trackingMonth').value=new Date().toISOString().slice(0,7);render()});document.addEventListener('click',e=>{const row=e.target.closest('[data-track-id]');if(row){selectedId=row.dataset.trackId;renderTable()}});if($('trackingMonth'))$('trackingMonth').value=new Date().toISOString().slice(0,7)},
 async refresh(){await loadModel();render();return model.length}
};
